#import "../../fragments/assessmentCompetencyParts.graphql"

query GetAssessment($assessmentId: ID!, $teacherView: Boolean! = true) {
  assessment(id: $assessmentId) {
    category
    code
    competencies {
      ...AssessmentCompetencyParts
    }
    description
    end
    evaluationRequest
    hasOralDefense
    id
    instances
    isIncremental
    isPhased
    load {
      defense
      grading
      work
    }
    name
    phases {
      competencies {
        ...AssessmentCompetencyParts
      }
      description
      name
    }
    provider
    providerConfig
    requireEvaluationRequestURL
    start
    takes
    type
  }
}
