query GetAssessment($assessmentId: ID!) {
  assessment(id: $assessmentId) {
    category
    code
    competencies {
      checklist {
        private
        public
      }
      competency {
        code
        name
      }
      isOptional
      learningOutcomes
      maxStars
      stars
    }
    description
    end
    evaluationRequest
    hasOralDefense
    id
    instances
    isIncremental
    load {
      defense
      grading
      work
    }
    name
    provider
    providerConfig
    start
    takes
    type
  }
}
