query GetCompetency($code: ID!) {
  competency(code: $code) {
    code
    description
    isPublic
    learningOutcomes {
      name
      takes
    }
    name
    partners {
      code
    }
    tags
    type
  }
}
