mutation AcceptEvaluationRequest($comment: String, $id: ID!) {
  acceptEvaluationRequest(comment: $comment, id: $id) {
    acceptanceComment
    accepted
    comment
    competencies {
      checklist {
        public
      }
      competency {
        code
      }
      learningOutcomes
      selected
    }
    evaluator {
      displayName
      username
    }
    id
    isRequestPending
    requestedCompetencies {
      checklist {
        public
      }
      competency {
        code
      }
      learningOutcomes
      selected
    }
    status
  }
}
