mutation CorrectEvaluation($id: ID!) {
  correctEvaluation(id: $id) {
    competencies {
      checklist {
        public
      }
      competency {
        code
      }
      learningOutcomes
      selected
    }
    data
    evaluator {
      displayName
      username
    }
    id
    isRequestPending
    published
    status
  }
}
