mutation CreateEvaluation(
  $assessment: ID!
  $comment: String
  $evalDate: DateTime
  $learner: ID!
) {
  createEvaluation(
    assessment: $assessment
    comment: $comment
    evalDate: $evalDate
    learner: $learner
  ) {
    id
  }
}
