mutation CreateEvaluation(
  $assessment: ID!
  $comment: String
  $competencies: [EvaluationCompetencyInput!]
  $evalDate: DateTime
  $instance: ID
  $learner: ID!
  $note: String
  $phase: Int
) {
  createEvaluation(
    assessment: $assessment
    comment: $comment
    competencies: $competencies
    evalDate: $evalDate
    instance: $instance
    learner: $learner
    note: $note
    phase: $phase
  ) {
    id
  }
}
