mutation EditEvaluation(
  $comment: String
  $competencies: [EvaluationCompetencyInput!]
  $evalDate: DateTime
  $id: ID!
  $note: String
) {
  editEvaluation(
    comment: $comment
    competencies: $competencies
    evalDate: $evalDate
    id: $id
    note: $note
  ) {
    comment
    competencies {
      checklist {
        private
        public
      }
      competency {
        code
      }
      learningOutcomes
      selected
    }
    date
    id
    note
  }
}
