query GetAssessment($courseCode: ID!, $assessmentId: ID!) {
  assessment(id: $assessmentId) {
    code
    description
    id
    name
    phases {
      description
      name
    }
  }

  course(code: $courseCode) {
    code
    isCoordinator
    isTeacher
  }
}
