query GetCourses {
  courses(view: TEACHER) {
    banner
    code
    coordinator {
      username
    }
    isArchived
    isCoordinator
    isPublished
    isTeacher
    name
    status
    type
    visibility
  }
}
