query GetCourseCalendar($courseCode: ID!) {
  course(code: $courseCode) {
    code
    isCoordinator
    isTeacher
    name
    schedule {
      name
      datetime
    }
  }

  events(courseCode: $courseCode) {
    end
    id
    start
    title
    type
  }
}
