query GetEvaluations($code: ID!) {
  course(code: $code) {
    code
    schedule {
      datetime
      name
    }
  }

  evaluations(courseCode: $code) {
    assessment {
      id
      code
      name
    }
    date
    id
    isPublished
    learner {
      displayName
      username
    }
  }
}
