query GetEvaluation($courseCode: ID!, $evaluationId: ID!) {
  course(code: $courseCode) {
    code
    isCoordinator
    isTeacher
  }

  evaluation(id: $evaluationId) {
    assessment {
      id
      name
    }
    comment
    competencies {
      checklist {
        public
      }
      competency {
        code
      }
      learningOutcomes
      selected
    }
    explanation
    id
    isPublished
    note
    status
  }
}
