#import "../fragments/evaluationCompetencyParts.graphql"

query GetEvaluation($courseCode: ID!, $evaluationId: ID!) {
  course(code: $courseCode) {
    code
    isCoordinator
    isTeacher
  }

  evaluation(id: $evaluationId) {
    acceptanceComment
    accepted
    assessment {
      hasProvider
      id
      name
      provider
      requireEvaluationRequestURL
    }
    comment
    competencies {
      checklist {
        private
        public
      }
      competency {
        code
      }
      learningOutcomes
      selected
    }
    data
    explanation
    id
    instance {
      content
      id
    }
    isPublished
    isRequestPending
    note
    pastCompetencies {
      ...EvaluationCompetencyParts
    }
    phase
    rejected
    rejectionReason
    requestedCompetencies {
      ...EvaluationCompetencyParts
    }
    status
    url
  }
}
