query GetAssessmentInfo($id: ID!, $teacherView: Boolean!) {
  assessment(id: $id) {
    evaluationRequest @include(if: $teacherView)
    hasOralDefense
    id
    instances
    load {
      defense
      work
    }
    takes
    type
  }
}
