query GetCourseRegistration($courseCode: ID!) {
  course(code: $courseCode) {
    code
    isCoordinator
    isRegistered
    isTeacher
    visibility
  }

  registration(code: $courseCode) {
    datetime
    id
    invitation
  }
}
