query GetEvaluationTakesInfo($id: ID!) {
  assessment(id: $id) {
    takesStatus {
      evaluations
      instances
      status
    }
    id
    instances
    isIncremental
    nbEvaluations
    nbInstances
  }
}
