query GetCourse($code: String!) {
    course(code: $code) {
        code
        colophon
        competencies {
            competency {
                code
                description
                name
            }
            category
            subcategory
        }
        description
        field
        language
        name
        schedule {
            name
            date
        }
        tags
        type
    }
}
