query GetPartner($code: String!) {
    partner(code: $code) {
        abbreviation
        code
        courses {
            banner
            code
            name
            type
        }
        description
        logo
        name
        website
    }
}
