query GetProgram($code: ID!) {
    program(code: $code) {
        code
        courses {
            banner
            code
            name
            type
        }
        description
        name
    }
}
