query GetPartner($code: ID!) {
  partner(code: $code) {
    abbreviation
    code
    courses {
      banner
      code
      name
      type
    }
    description
    logo
    name
    website
  }
}
