query GetAssessment($courseCode: ID!, $assessmentId: ID!) {
  assessment(id: $assessmentId) {
    canRequestEvaluation
    description
    id
    name
    phases {
      description
      name
    }
    provider
  }

  course(code: $courseCode) {
    code
    isRegistered
  }
}
