query GetCourseAssessments($courseCode: ID!) {
  assessments(courseCode: $courseCode) {
    category
    code
    id
    name
  }

  course(code: $courseCode) {
    code
    name
    schedule {
      name
      datetime
    }
  }

  registration(courseCode: $courseCode) {
    progress {
      advanced
      basic
    }
  }
}
