query GetCourseEvaluation($courseCode: ID!, $evaluationId: ID!) {
  evaluation(id: $evaluationId) {
    assessment {
      id
      name
    }
    comment
    competencies {
      checklist {
        public
      }
      competency {
        code
      }
      learningOutcomes
      selected
    }
    id
  }

  course(code: $courseCode) {
    code
    isRegistered
  }
}
