query GetCourseAssessment($courseCode: ID!, $assessmentId: ID!) {
  assessment(id: $assessmentId) {
    description
    id
    name
    provider
  }

  course(code: $courseCode) {
    code
    isRegistered
  }
}
