mutation RequestEvaluation(
  $assessment: ID!
  $competencies: [EvaluationCompetencyInput!]
  $explanation: String
  $instance: ID
  $phase: Int
) {
  requestEvaluation(
    assessment: $assessment
    competencies: $competencies
    explanation: $explanation
    instance: $instance
    phase: $phase
  ) {
    id
  }
}
