mutation CreateAssessment(
  $category: AssessmentCategory!
  $code: String
  $competencies: [AssessmentCompetencyInput!]!
  $course: ID!
  $description: String!
  $end: DateTime
  $name: String!
  $start: DateTime
  $workload: Int
) {
  createAssessment(
    category: $category
    code: $code
    competencies: $competencies
    course: $course
    description: $description
    end: $end
    name: $name
    start: $start
    workload: $workload
  ) {
    id
  }
}
