mutation createCompetency(
  $code: String!
  $description: String
  $name: String!
  $partners: [ID!]
  $public: Boolean
  $tags: [String!]
  $type: CompetencyType
) {
  createCompetency(
    code: $code
    description: $description
    name: $name
    partners: $partners
    public: $public
    tags: $tags
    type: $type
  )
}
