mutation CreateAssessment(
  $category: AssessmentCategory!
  $code: String
  $competencies: [AssessmentCompetencyInput!]!
  $course: ID!
  $createEvent: Boolean
  $description: String!
  $end: DateTime
  $incremental: Boolean
  $instances: Int
  $load: AssessmentLoadInput
  $name: String!
  $oralDefense: Boolean
  $start: DateTime
) {
  createAssessment(
    category: $category
    code: $code
    competencies: $competencies
    course: $course
    createEvent: $createEvent
    description: $description
    end: $end
    incremental: $incremental
    instances: $instances
    load: $load
    name: $name
    oralDefense: $oralDefense
    start: $start
  ) {
    id
  }
}
