mutation EditAssessment(
  $category: AssessmentCategory!
  $code: String
  $competencies: [AssessmentCompetencyInput!]!
  $createEvent: Boolean
  $description: String!
  $end: DateTime
  $evaluationRequest: Boolean
  $id: ID!
  $incremental: Boolean
  $instances: Int
  $load: AssessmentLoadInput
  $name: String!
  $oralDefense: Boolean
  $start: DateTime
  $takes: Int
) {
  editAssessment(
    category: $category
    code: $code
    competencies: $competencies
    createEvent: $createEvent
    description: $description
    end: $end
    evaluationRequest: $evaluationRequest
    id: $id
    incremental: $incremental
    instances: $instances
    load: $load
    name: $name
    oralDefense: $oralDefense
    start: $start
    takes: $takes
  ) {
    id
  }
}
