query GetCourses {
    courses(view: COORDINATOR) {
        banner
        code
        coordinator {
            id
            username
        }
        isArchived
        isCoordinator
        isPublished
        isTeacher
        name
        type
        visibility
    }
}
