query GetCourse($code: ID!) {
  course(code: $code) {
    archived
    code
    coordinator {
      displayName
      username
    }
    description
    isArchived
    isCoordinator
    isPublished
    name
    partners {
      abbreviation
      code
      name
    }
    published
    registrations {
      date
      email
      id
      invite
      user {
        displayName
        email
        username
      }
    }
    schedule {
      name
      date
    }
    teachers {
      displayName
      username
    }
    visibility
  }
}
