query GetCourseAssessments($courseCode: ID!) {
  assessments(courseCode: $courseCode) {
    category
    code
    competencies {
      competency {
        code
      }
      stars
    }
    end
    id
    isClosed
    isHidden
    name
    start
  }

  course(code: $courseCode) {
    code
    competencies {
      competency {
        code
        name
      }
      category
    }
    name
    schedule {
      name
      datetime
    }
  }
}
