query GetCourseAssessment($courseCode: ID!, $assessmentId: ID!) {
  course(code: $courseCode) {
    code
    name
  }

  assessment(id: $assessmentId) {
    code
    id
    name
    description
    start
    end
  }
}
