query GetCourseAssessment($courseCode: ID!, $assessmentId: ID!) {
  course(code: $courseCode) {
    code
    name
  }

  assessment(id: $assessmentId) {
    code
    description
    end
    id
    instances
    name
    start
    type
  }
}
