query GetCourseAssessments($code: ID!) {
  course(code: $code) {
    assessments {
      id
      name
      code
      competencies {
        competency {
          code
        }
        stars
      }
      end
      start
    }
    code
    name
    competencies {
      competency {
        code
        name
      }
      category
    }
    schedule {
      name
      datetime
    }
  }
}
