query GetCourseCompetencies($courseCode: ID!) {
  course(code: $courseCode) {
    code
    competencies {
      competency {
        code
        learningOutcomes
        name
      }
      useLearningOutcomes
    }
  }
}
