query GetCourseAssessment($courseCode: ID!, $assessmentId: ID!) {
  course(code: $courseCode) {
    code
    name
  }

  assessment(id: $assessmentId) {
    category
    code
    competencies {
      checklist {
        private
        public
      }
      competency {
        code
        name
      }
      isOptional
      learningOutcomes
      maxStars
      stars
    }
    description
    end
    hasOralDefense
    id
    instances
    isIncremental
    load {
      defense
      grading
      work
    }
    name
    provider
    providerConfig
    start
    type
  }
}
