query GetCompetency($code: ID!) {
  competency(code: $code) {
    code
    description
    isPublic
    learningOutcomes {
      name
      takes
    }
    name
    partners {
      abbreviation
      code
      name
    }
    tags
    type
    user {
      displayName
      username
    }
  }
}
