query GetProgram($code: ID!) {
  program(code: $code) {
    archived
    code
    courses {
      course {
        code
        name
        status
      }
    }
    description
    isArchived
    isCoordinator
    isPublished
    name
    published
    status
    visibility
  }
}
