query GetAssessmentsInfo($courseCode: ID!, $teacherView: Boolean!) {
  assessments(courseCode: $courseCode) {
    isClosed
    id
    isHidden @include(if: $teacherView)
  }

  course(code: $courseCode) {
    code
    isCoordinator
    isTeacher
  }
}
