query GetAssessmentsInfo(
  $courseCode: ID!
  $teacherView: Boolean!
  $hideTakesStatus: Boolean!
) {
  assessments(courseCode: $courseCode) {
    isClosed
    id
    isHidden @include(if: $teacherView)
    takesStatus @skip(if: $hideTakesStatus) {
      status
    }
  }

  course(code: $courseCode) {
    code
    isCoordinator
    isTeacher
  }
}
