query GetEvaluationsInfo($courseCode: ID!) {
  course(code: $courseCode) {
    code
    isCoordinator
    isTeacher
  }

  evaluations(courseCode: $courseCode) {
    id
    requested
    status
  }
}
