query GetAssessmentsInfo($courseCode: ID!) {
  course(code: $courseCode) {
    code
    groups {
      teaching {
        name
      }
      working {
        name
      }
    }
    teachers {
      displayName
      username
    }
  }
}
