query GetLearnersInfo($courseCode: ID!) {
  course (code: $courseCode) {
    code
    groups {
      teaching {
        supervisor {
          username
        }
      }
    }
  }

  registrations(confirmed: true, courseCode: $courseCode) {
    id
  }
}
