query GetAssessmentCompetencies($assessmentId: ID!, $courseCode: ID!, $teacherView: Boolean!) {
  assessment(id: $assessmentId) {
    code
    competencies {
      checklist {
        private @include(if: $teacherView)
        public
      }
      competency {
        code
        name
      }
      isOptional
      learningOutcomes
      maxStars
      stars
    }
    id
  }

  course(code: $courseCode) {
    code
    competencies {
      competency {
        code
        learningOutcomes {
          name
        }
      }
      useLearningOutcomes
    }
  }
}
