query GetAssessmentEvaluations($assessmentId: ID!) {
  evaluations(assessment: $assessmentId) {
    date
    id
    instance {
      id
    }
    status
  }

  instances(assessment: $assessmentId) {
    datetime
    id
  }
}
