query GetAssessmentsList($courseCode: ID!, $teacherView: Boolean!) {
  assessments(courseCode: $courseCode) {
    category
    code
    id
    isClosed
    isHidden @include(if: $teacherView)
    name
  }
}
