query GetCourseProgress($courseCode: ID!, $learner: ID) {
  course(code: $courseCode) {
    code
    competencies {
      category
      competency {
        code
        learningOutcomes {
          name
          takes
        }
        name
      }
      subcategory
      useLearningOutcomes
    }
    isCoordinator
    isRegistered
    isTeacher
  }

  registration(code: $courseCode, learner: $learner) {
    id
    progress {
      competencies {
        competency {
          code
        }
        learningOutcomes
        progress
      }
    }
  }
}
