query GetEvaluationsList(
  $assessmentId: ID
  $courseCode: ID!
  $published: Boolean
  $hideAssessment: Boolean!
  $hideLearner: Boolean!
) {
  evaluations(
    assessment: $assessmentId
    courseCode: $courseCode
    published: $published
  ) {
    assessment @skip(if: $hideAssessment) {
      id
      code
      name
    }
    date
    id
    learner @skip(if: $hideLearner) {
      displayName
      username
    }
    status
  }
}
