query GetEvaluationsList($courseCode: ID!) {
  evaluations(courseCode: $courseCode) {
    assessment {
      id
      code
      name
    }
    date
    id
    learner {
      displayName
      username
    }
    status
  }
}
