query GetPastEvaluations(
  $assessmentId: ID!
  $courseCode: ID!
  $learner: ID
  $massCreation: Boolean!
) {
  assessment(id: $assessmentId) {
    competencies {
      checklist {
        public
      }
      competency {
        code
      }
      learningOutcomes
    }
    id
    instances
    isIncremental
    takes
  }

  assessmentInstances(assessment: $assessmentId, learner: $learner)
    @skip(if: $massCreation) {
    datetime
    id
  }

  evaluations(assessment: $assessmentId, courseCode: $courseCode)
    @skip(if: $massCreation) {
    competencies {
      competency {
        code
      }
      learningOutcomes
      selected
    }
    id
    instance {
      id
    }
    isPublished
    learner {
      displayName
      username
    }
  }
}
